spring:
  data:
    elasticsearch: #ElasticsearchProperties
      cluster-name: elasticsearch #默认即为elasticsearch
      cluster-nodes: 192.168.160.138:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
server:
  port: 8080

logging:
  config: classpath:logback-spring.xml