server:
  port: 10000

spring:
  application:
    name: Spring-Gateway
  cloud:
    gateway:
      routes:
      - id: SPRING-TX-DEMO1
        uri: lb://SPRING-TX-DEMO1
        predicates:
        - Path=/SPRING-TX-DEMO1/**
      discovery:
        locator:
          enabled: true
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    appname: ${spring.application.name}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug