server:
  port: 8899
spring:
  redis:
    password: 123456
    host: www.redis.com
    port: 6379
    lettuce:
      pool:
        max-wait: -1ms
        max-active: 10
        max-idle: 5
        min-idle: 0
