时序图角色可以分为: actor, boundary, control, entity, database，每种角色呈现的图形也是不一样的
@startuml
title : 时序图角色
actor Foo1
boundary Foo2
control Foo3
entity Foo4
database Foo5
collections Foo6

Foo1->Foo1 : 1.1 do something
note left : write a remark
Foo1->Foo2 : 1.2 do something
Foo1->Foo3 : 1.3 answer your name
Foo1->Foo4 : 1.4 for myself
Foo1->Foo5 : 1.5 where are you
Foo1->Foo6 : 1.6 finish


@enduml