@startuml
Alice -> Bob: message 1
Bob --> Alice: message 2

newpage

Alice -> Bob: message 3
Alice <-- Bob: message 4

newpage A title for the \n last page

Alice -> Bob: message 5
Alice <-- Bob: message 6
@enduml