server:
  port: 8890

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/yinjihuan?characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
      max-active: 10
      min-idle: 5
  jpa:
    show-sql: true