server:
  port: 8081

spring:
  application:
    name: Spring-Pay
  datasource:
    druid:
      url: jdbc:mysql://192.168.160.142:3307/test?characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456

logging:
  config: classpath:logback-spring.xml

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    appname: ${spring.application.name}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

mybatis:
  type-aliases-package: com.jokey.bingo
  mapper-locations: classpath:mapper/*.xml
