spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://www.mysql.com:3306/ds0?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://www.mysql.com:3306/ds1?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    sharding:
      tables:
        t_order:
          actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
          ##指定分库规则
          database-strategy:
            ##行表达式
            inline:
              sharding-column: user_id
              algorithm-expression: ds$->{user_id % 2}
          ##指定分表规则
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order$->{order_id % 2}
          ## 生成分布式主键
          key-generator:
            column: order_id
            type: SNOWFLAKE

        t_order_item:
          actual-data-nodes: ds$->{0..1}.t_order_item$->{0..1}
          ##通过hint方式制定分库规则(因为item表没有user_id字段，只能通过hint策略自定义规则)
          database-strategy:
            hint:
              algorithmClassName: com.jokey.sharding.config.HintSharding
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_item$->{order_id % 2}
          ## 生成分布式主键
          key-generator:
            column: item_id
            type: SNOWFLAKE

      ## 绑定主表与子表，避免关联查询导致的全数据源路由
      binding-tables: t_order,t_order_item
      ## 配置广播表：以广播的形式保存（如果只涉及查询的话可以不配置，会随机取一个数据源）
      broadcast-tables: t_config
    ## 打印sql
    props:
      sql:
        show: true