#消息队列
message:
  queue:
    type: rabbitmq
## rabbit mq properties
rabbitmq:
  host: 192.168.160.142
  port: 5672
  username: guest
  password: guest
#spring:
#  rabbitmq:
#    host: 192.168.160.142
#    port: 5672
#    username: guest
#    password: guest
